name: Rust

on:
  pull_request:
    branches: [ prod ]
  
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        sharedKey: basic_log
    - name: Build
      run: cargo build --verbose
    
      
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
      with:
        sharedKey: basic_log
    - name: Run tests
      run: cargo test --verbose
