name: Rust

on:
  push:
    branches: [ prod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to cargo
      run: cargo login ${ secrets.CARGO_LOGIN }
    - name: Publish
      run: cargo publish
